version: 1.0.{build}

image: Ubuntu
stack: jdk 11
branches:
  only:
    - master
build: off  # будем использовать свой скрипт сборки
install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-mbank.jar &
build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации